<?php
$help_overview_text=<<<EOD

<p>
	<strong>Page scroll to id</strong> is an easy-to-use jQuery plugin that enables animated page scrolling to specific id within the document. 
</p>

<p>
	The plugin replaces the default browser behaviour of "jumping" to page sections when links with href value containing <code>#</code> are clicked, by smoothly animating the page to those sections. <br />
	You can use it for simple back-to-top links or complex, single-page website navigation and features include: adjustable animation speed, advanced animation easings, vertical and/or horizontal scrolling, links highlighting etc. 
</p>

<p>If you like this plugin and find it useful, consider making a <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UYJ5G65M6ZA28" target="_blank">donation</a> :)</p>

EOD;
?>

<?php _e($help_overview_text, $this->plugin_slug); ?>