<?php
$help_sidebar_text=<<<EOD

<p><strong>For more information</strong></p>

<ul>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id-for-wordpress-tutorial/" target="_blank">Page scroll to id for WordPress tutorial</a></li>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id" target="_blank">Plugin homepage</a></li>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id/2/" target="_blank">Code examples &amp; short tutorials</a></li>
</ul>

EOD;
?>

<?php _e($help_sidebar_text, $this->plugin_slug); ?>